name: beacon_scanner
description: 'A Flutter application for scanning IoT beacons.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  flutter_beacon: ^0.5.1
  google_sign_in: ^6.2.1
  icons_plus: ^5.0.0
  intl: ^0.19.0
  path: ^1.9.0
  permission_handler: ^11.3.1
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Italic.ttf
        - asset: fonts/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat-SemiBoldItalic.ttf
        - asset: fonts/Montserrat-Bold.ttf

  uses-material-design: true
